config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :occasions do
    member do
      get :add_gift
    end
  end

  resources :recipients
  resources :gifts
  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

root 'home#index'

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  has_many :occasions, dependent: :destroy
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user
    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:name, :street_address, :suburb, :state, :postcode, :relationship, :user_id, :country)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= simple_form_for(@recipient) do |f| %>
  <%= f.error_notification %>




  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :relationship, collection: ['Wife', 'Mother', 'Husband', 'Boyfriend', 'Girlfriend', 'Father'] %>
    <%= f.input :street_address %>
    <%= f.input :suburb %>
    <%= f.input :state %>
    <%= f.input :postcode %>
    <%= f.input :country %>
  
  </div>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing Recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street address</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Relationship</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.name %></td>
        <td><%= recipient.street_address %></td>
        <td><%= recipient.suburb %></td>
        <td><%= recipient.state %></td>
        <td><%= recipient.postcode %></td>
        <td><%= recipient.relationship %></td>
        <td><%= recipient.user %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New Recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @recipient.name %>
</p>


<p>
  <strong>Street address:</strong>
  <%= @recipient.street_address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @recipient.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @recipient.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @recipient.postcode %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @recipient.relationship %>
</p>

<%= link_to 'Add occassion', new_occasion_path(recipient: @recipient.id), class: 'btn btn-primary' %>





<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Show Recipients', recipients_path %>