config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :occasions do
    member do
      get :add_gift
    end
  end

  resources :recipients
  resources :gifts
  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

root 'home#index'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
	has_many :gift_occasions
	has_many :occasions, through: :gift_occasions

	mount_uploader :image, GiftImageUploader


	def self.order_by_name
		order(name: :asc)
	end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name, :description, :price, :image)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= simple_form_for(@gift) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <% if@gift.image %>
      <%= image_tag(@gift.image_url(:thumbnail)) %>
      <% end %>
    <%= f.input :image, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gifts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= link_to gift.name, gift_path(gift) %></td>
        <td><%= number_to_currency(gift.price) %></td>
        <td><%= image_tag gift.image, width: '50px' %></td>

        <td><%= link_to '<i class="fa fa-edit fa-2x"></i>'.html_safe, edit_gift_path(gift), title: 'Edit' %></td>
        <td><%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, gift, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path, class: 'btn btn-success' %>

app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-3">
	<%= image_tag(@gift.image_url(:normal), class: 'pull-left img-thumbnail') %>

  </div>
<div class="col-md-9">


  <h1><%= @gift.name %></h1>
<p><%= @gift.description %></p>

<p>

  <%= number_to_currency(@gift.price) %>
</p>

</div></div>