config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :occasions do
    member do
      get :add_gift
    end
  end

  resources :recipients
  resources :gifts
  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

root 'home#index'

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
	has_many :gift_occasions
	has_many :gifts, through: :gift_occasions
  belongs_to :recipient
  validates :occasion_type, :date, :recipient_id, presence: true
  validate :date_in_future

  def date_in_future
  	if date < Date.today + 7 
  		errors.add(:date, 'Must be earlier than 7 days in future')
  		end
	end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:add_gift, :show, :edit, :update, :destroy]

  def add_gift
    @gift = Gift.find(params[:gift])
    @occasion.gifts <<@gift
    redirect_to :back
  end


  # GET /occasions
  # GET /occasions.json
  def index
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
    @chosen_gifts = @occasion.gifts
    @gifts = Gift.all
  end

  # GET /occasions/new
  def new
    @occasion = Occasion.new
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = Occasion.new(occasion_params)

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:occasion_type, :date, :description, :message, :recipient_id)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= simple_form_for(@occasion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :occasion_type, collection: ['Wedding', 'Birthday', 'Anniversary', "Christmas"] %>
    <%= f.input :date %>
    <%= f.input :description %>
    <%= f.input :message %>
    <% if params[:recipient] %>
    <%= f.input :recipient_id, input_html: { value: params[:recipient] }, as: :hidden %>
<%end%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<h1>Editing Occasion</h1>

<%= render 'form' %>

<%= link_to 'Show', @occasion %> |
<%= link_to 'Back', occasions_path %>

app/views/occasions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Occasions</h1>

<table>
  <thead>
    <tr>
      <th>Occasion type</th>
      <th>Date</th>
      <th>Description</th>
      <th>Message</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.occasion_type %></td>
        <td><%= occasion.date %></td>
        <td><%= occasion.description %></td>
        <td><%= occasion.message %></td>
        <td><%= occasion.recipient %></td>
        <td><%= link_to 'Show', occasion %></td>
        <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
        <td><%= link_to 'Destroy', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occasion', new_occasion_path %>

app/views/occasions/new.html.erb
<h1>New Occasion</h1>

<%= render 'form' %>

<%= link_to 'Back', occasions_path %>

app/views/occasions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Occasion type:</strong>
  <%= @occasion.occasion_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @occasion.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @occasion.description %>
</p>

<p>
  <strong>Message:</strong>
  <%= @occasion.message %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @occasion.recipient.name if @occasion.recipient %>
</p>
      
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= link_to gift.name, gift_path(gift) %></td>
        <td><%= number_to_currency(gift.price) %></td>
        <td><%= image_tag gift.image, width: '50px' %></td>
        <td>
<% unless @occasion.gifts.include?(gift) %>
  <%= link_to 'Add to occasion', add_gift_occasion_path(gift: gift.id) %>
  <% end %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_occasion_path(@occasion) %> |
<%= link_to 'Back', occasions_path %>