config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :occasions do
    member do
      get :add_gift
    end
  end

  resources :recipients
  resources :gifts
  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    #authorize! edit, @account
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :phone, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Please enter your name' %>
    <%= f.input :phone, label: 'Your preferred contact number' %>
    
  </div>

  <div class="form-actions">
    <%= f.submit 'Completed Registration', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Completed Registration</h1>

<%= render 'form' %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.phone %></td>
        <td><%= account.user %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<div class="row">
	<div class="col-md-3">

		<div class="panel panel-info">

		<div class="panel-heading">

			<p class="panel-title">Your Account</p>
		</div>
		<div classe="panel-body">
	</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @account.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.user.email %>
</p>

<%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-warning' %> |

	</div>
  </div>
</div>
<div class="col-md-9">
	<div class="panel panel-info">
		<div class="panel-heading">
			<p class="panel-title">Recipients</p>
			</div>
			<div class="panel-body">
			<%= link_to 'Add a Recipient', new_recipient_path, class: 'btn btn-primary' %>
			<table class="table">

  <thead>
    <tr>
      <th>Name</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.recipients.each do |recipient| %>
      <tr>
        <td><%= link_to recipient.name, recipient %></td>
        <td><%= link_to 'Add Occassion', new_occasion_path(recipient: recipient.id), class: 'btn btn-info btn-xs' %></td>
        <td>
        	<% recipient.occasions.each do |occasion| %>
        	<p><%= occasion.occasion_type %></p>
        	<% end %>
        </td>	
        
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Delete', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
			</div>
		</div>
	</div>
</div>